version: "3.8"
services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-dev}
    container_name: app
    command: flask run --port 8080 --host 0.0.0.0
    environment:
      BOT_TOKEN: $BOT_TOKEN
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      FLASK_ENV: development
      FLASK_APP: main
      REBASE_URL: $REBASE_URL
    ports:
      - 8080:8080
    volumes:
      - ./config.py:/var/app/config.py
      - ./main.py:/var/app/main.py
      - ./app:/var/app/app
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.db/data:/var/lib/postgresql/data
