from .callback_query import callback_query
from .error import error
from .help_command import help_command
from .polo import polo
from .register import register
from .start import start
from .sticker import sticker
from .unknown import unknown
from .version import version
