from .callback_query import callback_query
from .cancel import cancel
from .error import error
from .help_command import help_command
from .new import new
from .polo import polo
from .register import register
from .start import start
from .sticker import sticker
from .text import text
from .unknown import unknown
from .version import version
