"""Initial migration.

Revision ID: e4ee0183e767
Revises: 
Create Date: 2022-11-20 17:05:05.735858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4ee0183e767'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribution_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('qr_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['attribution_label.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sticker_pack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=True),
    sa.Column('file_unique_id', sa.String(length=32), nullable=True),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['sticker_pack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribution_links',
    sa.Column('sticker_id', sa.Integer(), nullable=False),
    sa.Column('attribution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribution_id'], ['attribution.id'], ),
    sa.ForeignKeyConstraint(['sticker_id'], ['sticker.id'], ),
    sa.PrimaryKeyConstraint('sticker_id', 'attribution_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attribution_links')
    op.drop_table('sticker')
    op.drop_table('sticker_pack')
    op.drop_table('attribution')
    op.drop_table('user')
    op.drop_table('attribution_label')
    # ### end Alembic commands ###
